# Generated by Django 6.0.5 on 2026-05-20 19:56

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_maintenance_device", "0003_virtual_machine_and_calendar_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenanceplan",
            name="last_executed",
        ),
        migrations.AddField(
            model_name="maintenanceexecution",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="maintenanceplan",
            name="last_notified_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenanceplan",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
